workflows:
  # ============================================
  # iOS Build Workflow
  # ============================================
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: CozinhaAi
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cozinhaai
      node: 22
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Build web project
        script: |
          npm run build

      - name: Add iOS platform
        script: |
          npx cap add ios || true

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Fetch or create signing files
        script: |
          app-store-connect fetch-signing-files "com.cozinhaai" \
            --type IOS_APP_STORE \
            --create

      - name: Set up keychain
        script: |
          keychain initialize
          keychain add-certificates

      - name: Use profiles
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  # ============================================
  # Android Build Workflow
  # ============================================
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      android_signing:
        - cozinhai_keystore # Nome do keystore que você criar no CodeMagic
      java: 17
      node: 22
      vars:
        PACKAGE_NAME: "com.cozinhaai"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Build web project
        script: |
          npm run build

      - name: Add Android platform (if not exists)
        script: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Sync Capacitor Android
        script: |
          npx cap sync android

      - name: Build Android Release (AAB for Play Store)
        script: |
          cd android && ./gradlew bundleRelease

      - name: Build Android Release (APK for testing)
        script: |
          cd android && ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
